siteTitle = "Aquib Master - Blog"
siteDescr = "Frontend developer from Auckland, New Zealand."
siteAuthor = "Aquib Master"

siteTelegramUrl = "https://telegram.me/aquibm"
siteGithubUrl = "https://github.com/aquibm/"
siteEmailUrl = "mailto://aquibmaster@gmail.com"
siteRssUrl = "#"

linkPrefix = "/"