siteTitle = "Aquib Master - Blog"
siteDescr = "Web Developer from Auckland, New Zealand."
siteAuthor = "Aquib Master"

siteTelegramUrl = "https://telegram.me/aquibm"
siteGithubUrl = "https://github.com/aquibm/"
siteEmailUrl = "mailto://aquibmaster+blog@gmail.com"
siteRssUrl = "#"

linkPrefix = "//aquibm.com"